<!--
====================================================
Program Porter Stemming
====================================================
Generated by : Andi Sholihin
Email		 : dieka.91@gmail.com
Blog 		 : http://sekedar-tutorial.blogspot.com
====================================================
-->
<?php
$user = "root";
$pass = "";
$db = "skripsi";
$host = "localhost";
$konek = mysql_connect($host, $user, $pass);
mysql_select_db($db, $konek);
?>